# -*- coding: utf-8 -*-
"""
Token and TLS for the agent.

The agent launches processes on request, so an unauthenticated one is a remote
execution service. Both legs are therefore mandatory rather than optional:
the agent refuses to start without a token, and refuses to serve plaintext
unless explicitly forced for a local test.

Certificates are generated by shelling out to `openssl`, which is present on
every target distribution, rather than adding a dependency on `cryptography` to
a package that otherwise needs nothing.
"""

from __future__ import annotations

import hmac
import os
import secrets
import shutil
import ssl
import subprocess
from pathlib import Path
from typing import Optional

TOKEN_ENV = "QATREC_AGENT_TOKEN"
TOKEN_BYTES = 32


def generate_token() -> str:
    return secrets.token_urlsafe(TOKEN_BYTES)


def load_token(explicit: Optional[str] = None,
               token_file: Optional[str] = None) -> str:
    """Resolve the shared token, preferring the least leaky source.

    A token on the command line ends up in `ps` output and shell history, so a
    file or the environment is preferred; passing one directly is still allowed
    because it is convenient in a container.
    """
    if token_file:
        text = Path(token_file).read_text(encoding="utf-8").strip()
        if not text:
            raise ValueError(f"token file {token_file} is empty")
        return text
    if explicit:
        return explicit
    from_env = os.environ.get(TOKEN_ENV, "").strip()
    if from_env:
        return from_env
    raise ValueError(
        "no token: set QATREC_AGENT_TOKEN, pass --token-file, or run "
        "`qat-recorder-agent --generate-token`")


def token_matches(expected: str, presented: Optional[str]) -> bool:
    """Constant-time comparison, so a wrong token cannot be found byte by byte."""
    if not presented:
        return False
    return hmac.compare_digest(expected, presented)


def parse_bearer(header: Optional[str]) -> Optional[str]:
    if not header:
        return None
    parts = header.split(None, 1)
    if len(parts) != 2 or parts[0].lower() != "bearer":
        return None
    return parts[1].strip()


# ---------------------------------------------------------------------------
# TLS
# ---------------------------------------------------------------------------

def generate_self_signed(cert_path: str, key_path: str,
                         common_name: Optional[str] = None,
                         days: int = 825) -> tuple:
    """Write a self-signed certificate and key using the system `openssl`.

    Self-signed is appropriate here: the client pins the certificate's
    fingerprint, so there is no CA to trust and no name resolution to spoof.
    """
    if shutil.which("openssl") is None:
        raise RuntimeError(
            "openssl is required to generate a certificate; install it or "
            "supply --cert and --key from your own PKI")

    common_name = common_name or os.uname().nodename if hasattr(os, "uname") \
        else (common_name or "localhost")

    Path(cert_path).parent.mkdir(parents=True, exist_ok=True)
    Path(key_path).parent.mkdir(parents=True, exist_ok=True)

    subprocess.run(
        ["openssl", "req", "-x509", "-newkey", "rsa:2048", "-nodes",
         "-keyout", key_path, "-out", cert_path,
         "-days", str(days), "-subj", f"/CN={common_name}",
         "-addext", f"subjectAltName=DNS:{common_name},DNS:localhost,"
                    "IP:127.0.0.1"],
        check=True, capture_output=True)

    os.chmod(key_path, 0o600)
    return cert_path, key_path


def fingerprint(cert_path: str) -> str:
    """SHA-256 fingerprint, for the client to pin."""
    if shutil.which("openssl") is None:
        raise RuntimeError("openssl is required to read a fingerprint")
    result = subprocess.run(
        ["openssl", "x509", "-in", cert_path, "-noout", "-fingerprint",
         "-sha256"],
        check=True, capture_output=True, text=True)
    return result.stdout.strip().split("=", 1)[-1].replace(":", "").lower()


def server_context(cert_path: str, key_path: str) -> ssl.SSLContext:
    context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
    context.minimum_version = ssl.TLSVersion.TLSv1_2
    context.load_cert_chain(certfile=cert_path, keyfile=key_path)
    return context


def client_context(expected_fingerprint: Optional[str] = None,
                   ca_file: Optional[str] = None) -> ssl.SSLContext:
    """Client TLS.

    With a CA file, verify normally. Otherwise the agent is self-signed and the
    caller pins its fingerprint — the check happens after the handshake, in the
    client, because Python cannot express fingerprint pinning in the context
    itself. Hostname checking is off in that mode precisely because the pin, not
    the name, is what is being trusted.
    """
    context = ssl.SSLContext(ssl.PROTOCOL_TLS_CLIENT)
    context.minimum_version = ssl.TLSVersion.TLSv1_2
    if ca_file:
        context.load_verify_locations(cafile=ca_file)
        context.check_hostname = True
        context.verify_mode = ssl.CERT_REQUIRED
        return context
    if not expected_fingerprint:
        raise ValueError(
            "connecting without a CA requires a certificate fingerprint to pin")
    context.check_hostname = False
    context.verify_mode = ssl.CERT_NONE
    return context


def peer_fingerprint(connection) -> str:
    """SHA-256 of the certificate actually presented, to compare with the pin."""
    import hashlib
    der = connection.getpeercert(binary_form=True)
    if not der:
        raise AssertionError("peer presented no certificate")
    return hashlib.sha256(der).hexdigest()
