# -*- coding: utf-8 -*-
"""
Recording -> Gherkin feature plus step definitions.

Follows the layout Qat already ships in `qat/templates/steps/` (given/when/then
modules driven by an object dictionary) rather than inventing a parallel
convention.

The feature file names objects by label, never by definition. That keeps the
scenario readable by people who do not know Qt, and it means a re-resolved
recording changes only the object dictionary — the feature text stays put, so
its diff history stays meaningful.
"""

from __future__ import annotations

import re
from typing import Mapping

from qat_recorder.ir import ActionKind, Recording, Robustness, SECRET_KEY, is_secret

FEATURE_HEADER = """# Generated by qat-recorder from {source}.
# Object labels below are resolved by the OBJECTS dictionary in the generated
# step definitions; re-resolving objects changes that file, not this one.

Feature: {feature}
"""

STEPS_HEADER = '''"""
Step definitions for the generated feature.

Generated by qat-recorder from {source}. The object dictionary below is the only
part that changes when objects are re-resolved.
"""

import os

import qat
from behave import given, then, when

OBJECTS = {{
{objects}
}}

#: Where the application lives. `qat.start_application()` takes a registered
#: NAME, not a path, so without this the first run on any machine other than the
#: recording one fails with "Application '...' is not defined in configuration
#: file 'applications.json'".
APP_PATH = {app_path!r}


def secret(name):
    """Look up a value the recorder deliberately did not write to disk."""
    key = "QATREC_SECRET_" + name
    value = os.environ.get(key)
    if value is None:
        raise RuntimeError(
            "{{}} is not set; it holds a value the recorder redacted".format(key))
    return value


def obj(label):
    """Resolve a label from the feature file to a Qat object definition."""
    try:
        entry = OBJECTS[label]
    except KeyError:
        raise AssertionError("unknown object '{{}}'".format(label))
    if entry.get("index") is None:
        return entry["definition"]
    return qat.find_all_objects(entry["definition"])[entry["index"]]


@given('the application "{{name}}" is running')
def step_start_application(context, name):
    if APP_PATH and name not in qat.list_applications():
        qat.register_application(name, APP_PATH)
    context.app = qat.start_application(name)


@when('I click "{{label}}"')
def step_click(context, label):
    qat.mouse_click(obj(label))


@when('I right-click "{{label}}"')
def step_context_click(context, label):
    qat.mouse_click(obj(label), button=qat.Button.RIGHT)


@when('I double-click "{{label}}"')
def step_double_click(context, label):
    qat.double_click(obj(label))


@when('I type "{{value}}" into "{{label}}"')
def step_type(context, value, label):
    qat.type_in(obj(label), value)


@when('I type the secret "{{name}}" into "{{label}}"')
def step_type_secret(context, name, label):
    qat.type_in(obj(label), secret(name))


@when('I press "{{key}}" in "{{label}}"')
def step_press_key(context, key, label):
    qat.press_key(obj(label), key)


@when('I use the shortcut "{{keys}}" in "{{label}}"')
def step_shortcut(context, keys, label):
    qat.shortcut(obj(label), keys)


@then('"{{label}}" {{prop}} is "{{expected}}"')
def step_verify(context, label, prop, expected):
    actual = getattr(qat.wait_for_object(obj(label)), prop)
    assert str(actual) == expected, \\
        "expected {{}} to be {{!r}}, got {{!r}}".format(prop, expected, actual)
'''


def _escape(text: str) -> str:
    return str(text).replace('"', '\\"')


def _label_for(action, seen: dict) -> str:
    """A stable, unique, human-readable name for a target."""
    definition_key = repr(sorted(action.target.definition.items()))
    if definition_key in seen:
        return seen[definition_key]

    base = action.target.label or action.target.definition.get("type", "object")
    base = re.sub(r"\s+", " ", str(base)).strip() or "object"
    label = base
    suffix = 2
    existing = set(seen.values())
    while label in existing:
        label = f"{base} {suffix}"
        suffix += 1
    seen[definition_key] = label
    return label


def _step_for(action, label: str):
    """Return (keyword, sentence). The caller turns repeats into `And`."""
    if action.kind is ActionKind.CLICK:
        return "When", f'I click "{_escape(label)}"'
    if action.kind is ActionKind.CONTEXT_CLICK:
        return "When", f'I right-click "{_escape(label)}"'
    if action.kind is ActionKind.DOUBLE_CLICK:
        return "When", f'I double-click "{_escape(label)}"'
    if action.kind is ActionKind.TYPE:
        value = action.args.get("text", "")
        if is_secret(value):
            return "When", (f'I type the secret "{_escape(value[SECRET_KEY])}" '
                            f'into "{_escape(label)}"')
        return "When", f'I type "{_escape(value)}" into "{_escape(label)}"'
    if action.kind is ActionKind.KEY:
        return "When", (f'I press "{_escape(action.args.get("key", ""))}" '
                        f'in "{_escape(label)}"')
    if action.kind is ActionKind.SHORTCUT:
        return "When", (f'I use the shortcut "{_escape(action.args.get("keys", ""))}" '
                        f'in "{_escape(label)}"')
    if action.kind is ActionKind.VERIFY_PROPERTY:
        return "Then", (f'"{_escape(label)}" {action.args.get("property", "text")} '
                        f'is "{_escape(action.args.get("expected", ""))}"')
    return None, f"# unsupported action: {action.kind.value}"


def emit_gherkin(recording: Recording, feature: str = "Recorded session",
                 scenario: str = "Recorded session",
                 source: str = "recording.json") -> str:
    problems = recording.validate()
    if problems:
        raise ValueError("cannot emit an invalid recording: " + "; ".join(problems))

    seen: dict = {}
    lines = [FEATURE_HEADER.format(feature=feature, source=source)]
    lines.append(f"  Scenario: {scenario}")
    lines.append(f'    Given the application "{_escape(recording.app)}" is running')
    previous = "Given"

    for action in recording.actions:
        if action.kind is ActionKind.LAUNCH:
            continue
        if action.target is None:
            continue
        label = _label_for(action, seen)
        if action.target.robustness in (Robustness.WEAK, Robustness.FRAGILE):
            for warning in action.target.warnings:
                lines.append(f"    # {action.target.robustness.value}: {warning}")

        keyword, sentence = _step_for(action, label)
        if keyword is None:
            lines.append(f"    {sentence}")
            continue
        # Repeating a keyword is what makes generated Gherkin read like output
        # rather than like a specification. Chain with `And`.
        lines.append(f"    {'And' if keyword == previous else keyword} {sentence}")
        previous = keyword

    lines.append("")
    return "\n".join(lines)


def emit_steps(recording: Recording, source: str = "recording.json") -> str:
    """The step definitions and object dictionary for `emit_gherkin` output."""
    seen: dict = {}
    entries = []
    for action in recording.actions:
        if action.target is None:
            continue
        label = _label_for(action, seen)
        definition = dict(sorted(action.target.definition.items()))
        if any(entry.startswith(f'    "{label}"') for entry in entries):
            continue
        entries.append(
            f'    "{label}": {{"definition": {definition!r}, '
            f'"index": {action.target.index!r}}},')

    return STEPS_HEADER.format(source=source, objects="\n".join(entries),
                               app_path=recording.meta.get("app_path", ""))
