# -*- coding: utf-8 -*-
"""
Recording -> pytest module.

The generated file calls Qat's own API, so replay needs nothing from this project
at runtime. Two things are deliberate:

* **Fragile targets are flagged in the output.** A recording that depends on
  sibling ordering produces a script with a comment saying so, at the line that
  will break. Hiding it would make the script look more trustworthy than it is.
* **Secrets are never written.** A redacted value becomes a `secret()` lookup, so
  the file is safe to commit and fails loudly if the environment is not set up.
"""

from __future__ import annotations

import json
import keyword
import re
from typing import Any, Mapping

from qat_recorder.ir import ActionKind, Recording, Robustness, SECRET_KEY, is_secret

HEADER = '''"""
Generated by qat-recorder from a recorded session.

Regenerate rather than hand-edit: the recording in {source} is the source of
truth, and edits here are lost the next time it is re-emitted.
"""

import json
import os

import pytest
import qat


def secret(name):
    """Look up a value that was deliberately not recorded.

    The recorder saw a field with a non-normal echoMode and refused to write its
    contents to disk. Supply it through the environment at replay time.
    """
    key = "QATREC_SECRET_" + name
    value = os.environ.get(key)
    if value is None:
        raise RuntimeError(
            "{{}} is not set; it holds a value the recorder redacted".format(key))
    return value
'''

#: Added only when the recording uses a menu. Qat finds a menu item through the
#: menu that contains it, so a menu that is not open fails as though the menu
#: itself had vanished -- "Unable to find object: {"objectName":"menuOptions"}"
#: -- which sends you looking for the wrong problem entirely.
#: Always added. An application that gives a control no objectName leaves only
#: its visible text to identify it, and visible text changes when the product is
#: translated or reworded. Nothing can invent an identity the application does
#: not have -- but everything can be pointed at a better one from a single
#: place, instead of editing every test that touches the control.
OVERRIDE_HELPER = '''

def _overrides():
    """Definitions supplied by hand, from objects.json beside this test.

    An object map. Where the recorder could only find a control by its visible
    text, put a better definition here -- an objectName someone added to the
    application, an accessibleName, anything stable -- and every test that uses
    that control picks it up. Nothing is overridden by default.
    """
    here = os.path.dirname(os.path.abspath(__file__))
    try:
        with open(os.path.join(here, "objects.json"), encoding="utf-8") as file:
            loaded = json.load(file)
    except (OSError, ValueError):
        return {}
    return {name: value for name, value in loaded.items()
            if not name.startswith("_") and isinstance(value, dict)}


OVERRIDES = _overrides()


def override(name, definition):
    return OVERRIDES.get(name, definition)
'''

#: Added only when the recording touches a row of a list, tree or table. Qat
#: addresses items by row number, which is wrong the moment a row is inserted
#: above the one that matters. The text is what the person recognised, so the
#: text is what this looks for -- and the recorded row is kept as a fallback for
#: views whose items have no text at all.
ITEM_HELPER = '''

def row(container, text, column=0, recorded=0, limit=500):
    """The row of `container` showing `text`, wherever it has moved to.

    Falls back to the row that was recorded when nothing matches -- an item with
    no text, typically an icon or a checkbox column.
    """
    if text:
        for index in range(limit):
            candidate = {"container": container, "row": index, "column": column}
            try:
                item = qat.wait_for_object_exists(candidate, timeout=200)
            except LookupError:
                break
            if str(getattr(item, "text", "")) == text:
                item.ScrollTo()
                return candidate
        raise AssertionError(
            "no row of {} says {!r}. It was row {} when this was recorded; the "
            "contents have changed.".format(container, text, recorded))

    candidate = {"container": container, "row": recorded, "column": column}
    qat.wait_for_object_exists(candidate).ScrollTo()
    return candidate
'''

MENU_HELPER = '''

def menu_item(item):
    """Click a menu item, saying what actually went wrong if it is not there."""
    try:
        qat.mouse_click(item)
    except LookupError as error:
        raise AssertionError(
            "could not click the menu item {!r}: the menu holding it, {}, is "
            "not open. The step before this one should have opened it. If that "
            "step ran without complaint, something else had focus -- a dialog "
            "left open by an earlier step will do it.".format(
                item["text"], item["container"])) from error
'''


def is_item(definition: Any) -> bool:
    """Whether a definition addresses a row of a list, tree or table."""
    return isinstance(definition, Mapping) and "row" in definition \
        and "container" in definition


def is_menu_item(definition: Any) -> bool:
    """Whether a definition is Qat's form for a menu item.

    Recognised by shape rather than by the strategy that produced it, so a
    recording round-tripped through JSON is treated the same as a fresh one.
    """
    return (isinstance(definition, Mapping)
            and set(definition) == {"container", "text"})


def _identifier(text: str, fallback: str = "obj") -> str:
    cleaned = re.sub(r"[^0-9a-zA-Z_]+", "_", text or "").strip("_")
    if not cleaned:
        cleaned = fallback
    if cleaned[0].isdigit():
        cleaned = "_" + cleaned
    if keyword.iskeyword(cleaned):
        cleaned += "_"
    return cleaned


def _render(value: Any) -> str:
    """Render a value as a Python literal, with dict keys sorted for stability."""
    if is_secret(value):
        return f"secret({value[SECRET_KEY]!r})"
    if isinstance(value, Mapping):
        inner = ", ".join(f"{key!r}: {_render(value[key])}"
                          for key in sorted(value))
        return "{" + inner + "}"
    if isinstance(value, (list, tuple)):
        return "[" + ", ".join(_render(item) for item in value) + "]"
    return repr(value)


def _constant_names(recording: Recording) -> dict:
    """One module-level constant per distinct object definition."""
    names: dict = {}
    used: set = set()
    for action in recording.actions:
        if action.target is None:
            continue
        definition = action.target.definition
        label = action.target.label
        if is_item(definition):
            # The constant is the view; the row is chosen at run time, by text.
            # One constant per view rather than one per row keeps a script that
            # touches twenty rows readable.
            definition = definition["container"]
            label = (definition.get("objectName") or definition.get("type")
                     or "view")
        key = _render(definition)
        if key in names:
            continue
        base = _identifier(label, "object").upper()
        candidate = base
        suffix = 2
        while candidate in used:
            candidate = f"{base}_{suffix}"
            suffix += 1
        used.add(candidate)
        names[key] = candidate
    return names


def _target_expression(action, constants: dict) -> str:
    if is_item(action.target.definition):
        return _item_expression(action, constants)
    definition = _render(action.target.definition)
    name = constants[definition]
    if action.target.index is None:
        return name
    # Qat definitions have no index selector, so a positional target has to be
    # expressed as a lookup. It is fragile by construction and says so above.
    return f"qat.find_all_objects({name})[{action.target.index}]"


def _item_expression(action, constants: dict) -> str:
    """A row, looked up by the text it showed when it was recorded."""
    definition = action.target.definition
    view = constants[_render(definition["container"])]
    parts = [view, repr(action.target.item_text)]
    column = definition.get("column", 0)
    if column:
        parts.append(f"column={column}")
    parts.append(f"recorded={definition.get('row', 0)}")
    return f"row({', '.join(parts)})"


def _call_for(action, constants: dict) -> list:
    """Return the source lines for one action."""
    lines = []

    if action.target is not None:
        robustness = action.target.robustness
        if robustness in (Robustness.WEAK, Robustness.FRAGILE):
            for warning in action.target.warnings:
                lines.append(f"    # {robustness.value}: {warning}")

    if action.kind is ActionKind.LAUNCH:
        return lines

    if action.kind is ActionKind.CLOSE:
        lines.append("    qat.close_application()")
        return lines

    if action.kind is ActionKind.SCREENSHOT:
        path = action.args.get("path", "screenshot.png")
        lines.append(f"    qat.take_screenshot({path!r})")
        return lines

    target = _target_expression(action, constants)
    extra = ""
    if action.args.get("modifiers"):
        extra += f"  # with {action.args['modifiers']}"

    if action.kind is ActionKind.CLICK:
        button = action.args.get("button")
        if button == "right":
            lines.append(
                f"    qat.mouse_click({target}, button=qat.Button.RIGHT){extra}")
        elif is_menu_item(action.target.definition):
            lines.append(f"    menu_item({target}){extra}")
        else:
            lines.append(f"    qat.mouse_click({target}){extra}")
    elif action.kind is ActionKind.CONTEXT_CLICK:
        lines.append(
            f"    qat.mouse_click({target}, button=qat.Button.RIGHT){extra}")
    elif action.kind is ActionKind.DOUBLE_CLICK:
        lines.append(f"    qat.double_click({target}){extra}")
    elif action.kind is ActionKind.TYPE:
        lines.append(f"    qat.type_in({target}, {_render(action.args.get('text', ''))})")
    elif action.kind is ActionKind.KEY:
        lines.append(f"    qat.press_key({target}, {action.args.get('key', '')!r})")
    elif action.kind is ActionKind.SHORTCUT:
        lines.append(f"    qat.shortcut({target}, {action.args.get('keys', '')!r})")
    elif action.kind is ActionKind.SET_CHECKED:
        lines.append(f"    qat.mouse_click({target})")
    elif action.kind is ActionKind.SELECT:
        # A value, not the gesture that produced it. `wait_for_object` first
        # because the constant is a definition -- assigning to the dict itself
        # would set an attribute on a dictionary and change nothing in the
        # application.
        prop = action.args.get("property", "currentText")
        value = action.args.get("value")
        lines.append(f"    qat.wait_for_object({target}).{prop} = {_render(value)}")
    elif action.kind is ActionKind.VERIFY_PROPERTY:
        prop = action.args.get("property", "text")
        expected = action.args.get("expected")
        lines.append(f"    assert qat.wait_for_object({target}).{prop} == "
                     f"{_render(expected)}")
    elif action.kind is ActionKind.WHEEL:
        # Not produced by the recorder any more -- a scroll of so many degrees
        # depends on how much content happens to be there. Kept so recordings
        # made before that decision still generate.
        lines.append(f"    qat.mouse_wheel({target}, "
                     f"x_degrees={action.args.get('dx', 0)}, "
                     f"y_degrees={action.args.get('dy', 0)})")
    elif action.kind is ActionKind.DRAG:
        lines.append(f"    qat.mouse_drag({target}, dx={action.args.get('dx', 0)},"
                     f" dy={action.args.get('dy', 0)})")
    elif action.kind is ActionKind.WAIT_MISSING:
        lines.append(f"    qat.wait_for_object_missing({target})")
    else:
        lines.append(f"    # unsupported action: {action.kind.value}")

    if action.note:
        lines[-1] += f"  # {action.note}"
    return lines


#: Qat waits three seconds for an object. That is fine for a button and not for
#: a dialog that has to read a file, so the wait is derived from the recording
#: instead: the pauses a person left between actions are evidence of how long
#: this application makes them wait. Doubled, floored, and capped so a
#: recording where somebody went for coffee does not produce a test that hangs
#: for an hour.
MIN_TIMEOUT_MS = 10_000
MAX_TIMEOUT_MS = 120_000


def derived_timeout(recording: Recording) -> int:
    times = [action.t for action in recording.actions]
    gaps = [later - earlier for earlier, later in zip(times, times[1:])]
    longest = max(gaps) if gaps else 0.0
    return int(min(MAX_TIMEOUT_MS, max(MIN_TIMEOUT_MS, longest * 2000)))


def _timeout_block(recording: Recording) -> list:
    timeout = derived_timeout(recording)
    return [
        "",
        "# How long to wait for an object. Qat's own default is 3s; this is",
        "# taken from the longest pause in the recorded session, because that is",
        "# how long this application actually kept someone waiting.",
        f"TIMEOUT_MS = int(os.environ.get('QATREC_TIMEOUT_MS') or {timeout})",
    ]


def _preconditions(items: list, constants: dict) -> list:
    """A check, before anything is touched, of what the recording assumed.

    A test recorded against a torrent called ubuntu.iso needs that row to exist.
    Without this it half-runs and fails somewhere in the middle, leaving dialogs
    open and the application in a state nobody chose. Failing first, naming
    everything that is missing at once, is worth more than failing early on the
    first of them.
    """
    wanted = []
    seen = set()
    for action in items:
        text = action.target.item_text
        if not text:
            continue
        view = constants[_render(action.target.definition["container"])]
        key = (view, text)
        if key in seen:
            continue
        seen.add(key)
        wanted.append((view, text, action.target.definition.get("row", 0)))

    if not wanted:
        return []

    lines = ["", "def preconditions():",
             '    """What this recording assumes was already on screen."""',
             "    missing = []"]
    for view, text, recorded in wanted:
        lines.append(f"    try:")
        lines.append(f"        row({view}, {text!r}, recorded={recorded})")
        lines.append(f"    except (AssertionError, LookupError):")
        lines.append(f"        missing.append({text!r} + ' in ' + str({view}))")
    lines.extend([
        "    if missing:",
        "        raise AssertionError(",
        "            'this test was recorded against data that is not here: '",
        "            + ', '.join(missing) +",
        "            '. Put the application into that state, or re-record.')",
        "",
    ])
    return lines


def emit_object_map(recording: Recording) -> str:
    """The object map that ships beside a generated test.

    Empty of overrides on purpose: nothing should change behind the operator's
    back. What it does carry is the list of controls the application gave no
    durable identity, with the definition the recorder settled for, so fixing
    one is copying a line up and editing it rather than working out what to
    write from nothing.
    """
    constants = _constant_names(recording)
    weak = {}
    for action in recording.actions:
        target = action.target
        if target is None or target.robustness not in (
                Robustness.WEAK, Robustness.FRAGILE):
            continue
        definition = target.definition
        if is_item(definition):
            definition = definition["container"]
        name = constants.get(_render(definition))
        if name and name not in weak:
            weak[name] = dict(definition)

    document = {
        "_help": [
            "Definitions supplied by hand. Anything at the top level of this "
            "file replaces what the recorder worked out, for every test in "
            "this folder.",
            "Copy an entry out of _weak, put it at the top level, and edit it "
            "-- an objectName someone added to the application, an "
            "accessibleName, any property that does not change when the "
            "product is translated.",
            "Nothing is overridden while this file has no top-level entries.",
        ],
        "_weak": weak,
    }
    return json.dumps(document, indent=2, sort_keys=False) + "\n"


def emit_python(recording: Recording, test_name: str = "test_recorded_session",
                source: str = "recording.json") -> str:
    problems = recording.validate()
    if problems:
        raise ValueError("cannot emit an invalid recording: " + "; ".join(problems))

    constants = _constant_names(recording)

    out = [HEADER.format(source=source), ""]
    definitions = [action.target.definition for action in recording.actions
                   if action.target is not None]
    out.append(OVERRIDE_HELPER)
    if any(is_menu_item(definition) for definition in definitions):
        out.append(MENU_HELPER)
    items = [action for action in recording.actions
             if action.target is not None and is_item(action.target.definition)]
    if items:
        out.append(ITEM_HELPER)

    for definition, name in constants.items():
        out.append(f"{name} = override({name!r}, {definition})")
    if constants:
        out.append("")

    out.append("")
    out.append(f"APP_NAME = {recording.app!r}")
    app_path = recording.meta.get("app_path", "")
    if app_path:
        out.append(f"APP_PATH = {app_path!r}")
    out.extend(_timeout_block(recording))
    out.append("")
    out.append("")
    out.append("@pytest.fixture()")
    out.append("def application():")
    if app_path:
        # Register it here rather than expecting the operator to have done so.
        # `start_application` takes a registered NAME, so a test that only knows
        # the name fails with "Application '...' is not defined in configuration
        # file 'applications.json'" on any machine where it was not registered
        # first -- which is every machine except the one it was recorded on.
        out.append("    if APP_NAME not in qat.list_applications():")
        out.append("        qat.register_application(APP_NAME, APP_PATH)")
    out.append("    qat.Settings.wait_for_object_timeout = TIMEOUT_MS")
    out.append("    # The same condition the session was recorded under: Qt's")
    out.append("    # own file dialogs rather than the desktop's. A native")
    out.append("    # dialog is not a Qt widget -- Qat cannot see it, and while")
    out.append("    # one is open the application stops answering Qat at all.")
    out.append("    if os.environ.get('QATREC_NATIVE_DIALOGS') != '1':")
    out.append("        os.environ['QT_QPA_PLATFORMTHEME'] = ''")
    out.append("    context = qat.start_application(APP_NAME)")
    out.append("    yield context")
    out.append("    qat.close_application(context)")
    out.append("")
    out.extend(_preconditions(items, constants))
    out.append("")
    out.append(f"def {_identifier(test_name, 'test_recorded')}(application):")

    body = []
    if items:
        body.append("    preconditions()")
    for action in recording.actions:
        body.extend(_call_for(action, constants))
    if not body:
        body.append("    pass")
    out.extend(body)
    out.append("")

    weakest = recording.weakest_targets()
    if weakest:
        out.append("")
        out.append("# Review before relying on this script:")
        for action in weakest:
            out.append(f"#   {action.target.robustness.value:<10} "
                       f"{action.target.label} -> {action.target.definition}")
        out.append("")

    return "\n".join(out)
