# -*- coding: utf-8 -*-
"""
Recording -> pytest module.

The generated file calls Qat's own API, so replay needs nothing from this project
at runtime. Two things are deliberate:

* **Fragile targets are flagged in the output.** A recording that depends on
  sibling ordering produces a script with a comment saying so, at the line that
  will break. Hiding it would make the script look more trustworthy than it is.
* **Secrets are never written.** A redacted value becomes a `secret()` lookup, so
  the file is safe to commit and fails loudly if the environment is not set up.
"""

from __future__ import annotations

import keyword
import re
from typing import Any, Mapping

from qat_recorder.ir import ActionKind, Recording, Robustness, SECRET_KEY, is_secret

HEADER = '''"""
Generated by qat-recorder from a recorded session.

Regenerate rather than hand-edit: the recording in {source} is the source of
truth, and edits here are lost the next time it is re-emitted.
"""

import os

import pytest
import qat


def secret(name):
    """Look up a value that was deliberately not recorded.

    The recorder saw a field with a non-normal echoMode and refused to write its
    contents to disk. Supply it through the environment at replay time.
    """
    key = "QATREC_SECRET_" + name
    value = os.environ.get(key)
    if value is None:
        raise RuntimeError(
            "{{}} is not set; it holds a value the recorder redacted".format(key))
    return value
'''

#: Added only when the recording uses a menu. Qat finds a menu item through the
#: menu that contains it, so a menu that is not open fails as though the menu
#: itself had vanished -- "Unable to find object: {"objectName":"menuOptions"}"
#: -- which sends you looking for the wrong problem entirely.
#: Added only when the recording touches a row of a list, tree or table. Qat
#: addresses items by row number, which is wrong the moment a row is inserted
#: above the one that matters. The text is what the person recognised, so the
#: text is what this looks for -- and the recorded row is kept as a fallback for
#: views whose items have no text at all.
ITEM_HELPER = '''

def row(container, text, column=0, recorded=0, limit=500):
    """The row of `container` showing `text`, wherever it has moved to.

    Falls back to the row that was recorded when nothing matches -- an item with
    no text, typically an icon or a checkbox column.
    """
    if text:
        for index in range(limit):
            candidate = {"container": container, "row": index, "column": column}
            try:
                item = qat.wait_for_object_exists(candidate, timeout=200)
            except LookupError:
                break
            if str(getattr(item, "text", "")) == text:
                item.ScrollTo()
                return candidate
        raise AssertionError(
            "no row of {} says {!r}. It was row {} when this was recorded; the "
            "contents have changed.".format(container, text, recorded))

    candidate = {"container": container, "row": recorded, "column": column}
    qat.wait_for_object_exists(candidate).ScrollTo()
    return candidate
'''

MENU_HELPER = '''

def menu_item(item):
    """Click a menu item, saying what actually went wrong if it is not there."""
    try:
        qat.mouse_click(item)
    except LookupError as error:
        raise AssertionError(
            "could not click the menu item {!r}: the menu holding it, {}, is "
            "not open. The step before this one should have opened it. If that "
            "step ran without complaint, something else had focus -- a dialog "
            "left open by an earlier step will do it.".format(
                item["text"], item["container"])) from error
'''


def is_item(definition: Any) -> bool:
    """Whether a definition addresses a row of a list, tree or table."""
    return isinstance(definition, Mapping) and "row" in definition \
        and "container" in definition


def is_menu_item(definition: Any) -> bool:
    """Whether a definition is Qat's form for a menu item.

    Recognised by shape rather than by the strategy that produced it, so a
    recording round-tripped through JSON is treated the same as a fresh one.
    """
    return (isinstance(definition, Mapping)
            and set(definition) == {"container", "text"})


def _identifier(text: str, fallback: str = "obj") -> str:
    cleaned = re.sub(r"[^0-9a-zA-Z_]+", "_", text or "").strip("_")
    if not cleaned:
        cleaned = fallback
    if cleaned[0].isdigit():
        cleaned = "_" + cleaned
    if keyword.iskeyword(cleaned):
        cleaned += "_"
    return cleaned


def _render(value: Any) -> str:
    """Render a value as a Python literal, with dict keys sorted for stability."""
    if is_secret(value):
        return f"secret({value[SECRET_KEY]!r})"
    if isinstance(value, Mapping):
        inner = ", ".join(f"{key!r}: {_render(value[key])}"
                          for key in sorted(value))
        return "{" + inner + "}"
    if isinstance(value, (list, tuple)):
        return "[" + ", ".join(_render(item) for item in value) + "]"
    return repr(value)


def _constant_names(recording: Recording) -> dict:
    """One module-level constant per distinct object definition."""
    names: dict = {}
    used: set = set()
    for action in recording.actions:
        if action.target is None:
            continue
        definition = action.target.definition
        label = action.target.label
        if is_item(definition):
            # The constant is the view; the row is chosen at run time, by text.
            # One constant per view rather than one per row keeps a script that
            # touches twenty rows readable.
            definition = definition["container"]
            label = (definition.get("objectName") or definition.get("type")
                     or "view")
        key = _render(definition)
        if key in names:
            continue
        base = _identifier(label, "object").upper()
        candidate = base
        suffix = 2
        while candidate in used:
            candidate = f"{base}_{suffix}"
            suffix += 1
        used.add(candidate)
        names[key] = candidate
    return names


def _target_expression(action, constants: dict) -> str:
    if is_item(action.target.definition):
        return _item_expression(action, constants)
    definition = _render(action.target.definition)
    name = constants[definition]
    if action.target.index is None:
        return name
    # Qat definitions have no index selector, so a positional target has to be
    # expressed as a lookup. It is fragile by construction and says so above.
    return f"qat.find_all_objects({name})[{action.target.index}]"


def _item_expression(action, constants: dict) -> str:
    """A row, looked up by the text it showed when it was recorded."""
    definition = action.target.definition
    view = constants[_render(definition["container"])]
    parts = [view, repr(action.target.item_text)]
    column = definition.get("column", 0)
    if column:
        parts.append(f"column={column}")
    parts.append(f"recorded={definition.get('row', 0)}")
    return f"row({', '.join(parts)})"


def _call_for(action, constants: dict) -> list:
    """Return the source lines for one action."""
    lines = []

    if action.target is not None:
        robustness = action.target.robustness
        if robustness in (Robustness.WEAK, Robustness.FRAGILE):
            for warning in action.target.warnings:
                lines.append(f"    # {robustness.value}: {warning}")

    if action.kind is ActionKind.LAUNCH:
        return lines

    if action.kind is ActionKind.CLOSE:
        lines.append("    qat.close_application()")
        return lines

    if action.kind is ActionKind.SCREENSHOT:
        path = action.args.get("path", "screenshot.png")
        lines.append(f"    qat.take_screenshot({path!r})")
        return lines

    target = _target_expression(action, constants)
    extra = ""
    if action.args.get("modifiers"):
        extra += f"  # with {action.args['modifiers']}"

    if action.kind is ActionKind.CLICK:
        button = action.args.get("button")
        if button == "right":
            lines.append(
                f"    qat.mouse_click({target}, button=qat.Button.RIGHT){extra}")
        elif is_menu_item(action.target.definition):
            lines.append(f"    menu_item({target}){extra}")
        else:
            lines.append(f"    qat.mouse_click({target}){extra}")
    elif action.kind is ActionKind.CONTEXT_CLICK:
        lines.append(
            f"    qat.mouse_click({target}, button=qat.Button.RIGHT){extra}")
    elif action.kind is ActionKind.DOUBLE_CLICK:
        lines.append(f"    qat.double_click({target}){extra}")
    elif action.kind is ActionKind.TYPE:
        lines.append(f"    qat.type_in({target}, {_render(action.args.get('text', ''))})")
    elif action.kind is ActionKind.KEY:
        lines.append(f"    qat.press_key({target}, {action.args.get('key', '')!r})")
    elif action.kind is ActionKind.SHORTCUT:
        lines.append(f"    qat.shortcut({target}, {action.args.get('keys', '')!r})")
    elif action.kind is ActionKind.SET_CHECKED:
        lines.append(f"    qat.mouse_click({target})")
    elif action.kind is ActionKind.SELECT:
        # A value, not the gesture that produced it. `wait_for_object` first
        # because the constant is a definition -- assigning to the dict itself
        # would set an attribute on a dictionary and change nothing in the
        # application.
        prop = action.args.get("property", "currentText")
        value = action.args.get("value")
        lines.append(f"    qat.wait_for_object({target}).{prop} = {_render(value)}")
    elif action.kind is ActionKind.VERIFY_PROPERTY:
        prop = action.args.get("property", "text")
        expected = action.args.get("expected")
        lines.append(f"    assert qat.wait_for_object({target}).{prop} == "
                     f"{_render(expected)}")
    elif action.kind is ActionKind.WHEEL:
        # Not produced by the recorder any more -- a scroll of so many degrees
        # depends on how much content happens to be there. Kept so recordings
        # made before that decision still generate.
        lines.append(f"    qat.mouse_wheel({target}, "
                     f"x_degrees={action.args.get('dx', 0)}, "
                     f"y_degrees={action.args.get('dy', 0)})")
    elif action.kind is ActionKind.DRAG:
        lines.append(f"    qat.mouse_drag({target}, dx={action.args.get('dx', 0)},"
                     f" dy={action.args.get('dy', 0)})")
    elif action.kind is ActionKind.WAIT_MISSING:
        lines.append(f"    qat.wait_for_object_missing({target})")
    else:
        lines.append(f"    # unsupported action: {action.kind.value}")

    if action.note:
        lines[-1] += f"  # {action.note}"
    return lines


def emit_python(recording: Recording, test_name: str = "test_recorded_session",
                source: str = "recording.json") -> str:
    problems = recording.validate()
    if problems:
        raise ValueError("cannot emit an invalid recording: " + "; ".join(problems))

    constants = _constant_names(recording)

    out = [HEADER.format(source=source), ""]
    definitions = [action.target.definition for action in recording.actions
                   if action.target is not None]
    if any(is_menu_item(definition) for definition in definitions):
        out.append(MENU_HELPER)
    if any(is_item(definition) for definition in definitions):
        out.append(ITEM_HELPER)

    for definition, name in constants.items():
        out.append(f"{name} = {definition}")
    if constants:
        out.append("")

    out.append("")
    out.append(f"APP_NAME = {recording.app!r}")
    app_path = recording.meta.get("app_path", "")
    if app_path:
        out.append(f"APP_PATH = {app_path!r}")
    out.append("")
    out.append("")
    out.append("@pytest.fixture()")
    out.append("def application():")
    if app_path:
        # Register it here rather than expecting the operator to have done so.
        # `start_application` takes a registered NAME, so a test that only knows
        # the name fails with "Application '...' is not defined in configuration
        # file 'applications.json'" on any machine where it was not registered
        # first -- which is every machine except the one it was recorded on.
        out.append("    if APP_NAME not in qat.list_applications():")
        out.append("        qat.register_application(APP_NAME, APP_PATH)")
    out.append("    context = qat.start_application(APP_NAME)")
    out.append("    yield context")
    out.append("    qat.close_application(context)")
    out.append("")
    out.append("")
    out.append(f"def {_identifier(test_name, 'test_recorded')}(application):")

    body = []
    for action in recording.actions:
        body.extend(_call_for(action, constants))
    if not body:
        body.append("    pass")
    out.extend(body)
    out.append("")

    weakest = recording.weakest_targets()
    if weakest:
        out.append("")
        out.append("# Review before relying on this script:")
        for action in weakest:
            out.append(f"#   {action.target.robustness.value:<10} "
                       f"{action.target.label} -> {action.target.definition}")
        out.append("")

    return "\n".join(out)
